In [1]:
import numpy as np

In [4]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
a.fill(2)
a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [8]:
a += 5
a

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [9]:
a -= 5
a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [10]:
a *= 5
a

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

### Element-wise Operations: 

In [35]:
array1 = np.array([[1., 2., 3.],
                   [2., 4., 4.],
                   [9., 6., 7.]])

In [36]:
array2 = np.array([[5., 4., 3.],
                  [9., 7., 3.],
                  [1., 5., 6.]])

In [37]:
sum_ops = array1 +array2 
sum_ops

array([[ 6.,  6.,  6.],
       [11., 11.,  7.],
       [10., 11., 13.]])

In [39]:
dif_ops = array1  - array2 
dif_ops

array([[-4., -2.,  0.],
       [-7., -3.,  1.],
       [ 8.,  1.,  1.]])

In [40]:
mul_ops = array1  * array2 
mul_ops

array([[ 5.,  8.,  9.],
       [18., 28., 12.],
       [ 9., 30., 42.]])

In [41]:
rand_ops = ((5 * array1  * array2) + array1) / 4
rand_ops

array([[ 6.5 , 10.5 , 12.  ],
       [23.  , 36.  , 16.  ],
       [13.5 , 39.  , 54.25]])

In [56]:
array1 = np.arange(1,10).reshape(3,3)
array2 = np.ones((3,3)) + 1
module = array1 % array2
print("array1 : \n" , array1)
print("array2 : \n" , array2)
module 

array1 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2 : 
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])

In [51]:
array1 = np.ones((3,3)) + 1
array1

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [59]:
floor_divition = array1 // array2  # remove the decimal points
print (array1 / array2)
floor_divition

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


array([[0., 1., 1.],
       [2., 2., 3.],
       [3., 4., 4.]])

In [61]:
np.floor(array1/array2) # same as floor_divition

array([[0., 1., 1.],
       [2., 2., 3.],
       [3., 4., 4.]])

### Matrix Multiplication:

In [65]:
array1 = np.arange(1,10).reshape(3,3)
array2 = np.arange(5,14).reshape(3,3)
print("array1 : \n" , array1)
print("array2 : \n" , array2)

array1 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2 : 
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [66]:
matrix_multiplication = np.matmul(array1,array2)
matrix_multiplication

array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]])

In [67]:
print(array1 * array2)

[[  5  12  21]
 [ 32  45  60]
 [ 77  96 117]]


### Reduction Operations:

In [19]:
original_array = np.array([[1., 2., 3.],
                           [2., 4., 4.],
                           [9., 6., 7.]])
original_array

array([[1., 2., 3.],
       [2., 4., 4.],
       [9., 6., 7.]])

In [20]:
original_array.sum()

38.0

In [21]:
original_array.sum(1)  # sum of every row

array([ 6., 10., 22.])

In [24]:
original_array.sum(axis = 0) # sum of every column

array([12., 12., 14.])

In [25]:
original_array.prod()

72576.0

In [26]:
original_array.prod(axis = 1)

array([  6.,  32., 378.])

In [28]:
original_array.mean()

4.222222222222222

In [29]:
original_array.min()

1.0

In [30]:
original_array.max()

9.0

In [31]:
original_array.argmax() # index of maximum value

6

In [32]:
original_array.argmin()  # index of minimum value

0

In [34]:
peak_to_peak = original_array.ptp() # ptp() = maxmium value - minimum value 
peak_to_peak

8.0

### Indexing and Slicing:

In [68]:
my_array = [10, 20, 30, 40, 50]

In [70]:
my_array[3]

40

In [71]:
my_array[2]

30

In [73]:
my_array[2:4]

[30, 40]

### Element-wise Functions:

In [74]:
data = np.array([1, 2, 3])
np.exp(data)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [75]:
data = np.array([4, 9, 16])
np.sqrt(data)

array([2., 3., 4.])

In [76]:
data = np.array([1, 10, 100])
np.log(data)

array([0.        , 2.30258509, 4.60517019])