### Reshaping Arrays

In [2]:
import numpy as np

In [3]:
ary = np.array([[1,2,3],[4,5,6],[7,8,9]])
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
ary.shape

(3, 3)

In [8]:
age_students = np.array([21, 21, 21, 20, 20, 20, 19, 19, 19])
age_students

array([21, 21, 21, 20, 20, 20, 19, 19, 19])

In [9]:
score_students = np.array([56, 57, 58, 23, 89, 45, 67, 45, 45])
score_students

array([56, 57, 58, 23, 89, 45, 67, 45, 45])

In [10]:
exam_split = score_students.reshape(3, 3)
exam_split

array([[56, 57, 58],
       [23, 89, 45],
       [67, 45, 45]])

### Transposing and Swapping Axes

In [11]:
ary.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
original_array = np.array([[[1, 2],
                            [3, 4]],
                           
                           [[5, 6],
                            [7, 8]]])

In [24]:
swapped_array = np.swapaxes(original_array, 1,0)
swapped_array

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

### Joining Arrays (concatenation)

In [25]:
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
ary2= np.random.rand(3,3)
ary2

array([[0.06638163, 0.45159256, 0.04686374],
       [0.93371376, 0.99375808, 0.29366182],
       [0.37827659, 0.23791239, 0.69751077]])

In [33]:
# Vertical concatenation
vertical_concatenated = np.vstack((ary,ary2))
vertical_concatenated 

array([[1.        , 2.        , 3.        ],
       [4.        , 5.        , 6.        ],
       [7.        , 8.        , 9.        ],
       [0.06638163, 0.45159256, 0.04686374],
       [0.93371376, 0.99375808, 0.29366182],
       [0.37827659, 0.23791239, 0.69751077]])

In [34]:
# horizontal concatenation
horizontal_concatenated = np.hstack((ary,ary2))
horizontal_concatenated

array([[1.        , 2.        , 3.        , 0.06638163, 0.45159256,
        0.04686374],
       [4.        , 5.        , 6.        , 0.93371376, 0.99375808,
        0.29366182],
       [7.        , 8.        , 9.        , 0.37827659, 0.23791239,
        0.69751077]])

### Splitting Arrays

In [60]:
vertical_concatenated

array([[1.        , 2.        , 3.        ],
       [4.        , 5.        , 6.        ],
       [7.        , 8.        , 9.        ],
       [0.06638163, 0.45159256, 0.04686374],
       [0.93371376, 0.99375808, 0.29366182],
       [0.37827659, 0.23791239, 0.69751077]])

In [68]:
A, B = np.vsplit(vertical_concatenated, 2)

In [69]:
A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [70]:
B

array([[0.06638163, 0.45159256, 0.04686374],
       [0.93371376, 0.99375808, 0.29366182],
       [0.37827659, 0.23791239, 0.69751077]])

In [46]:
random_array = np.random.rand(4,4)
random_array 

array([[0.98708152, 0.61235283, 0.95699754, 0.75067718],
       [0.81031061, 0.77476048, 0.07428372, 0.62770638],
       [0.93603482, 0.54644815, 0.51919619, 0.47061915],
       [0.42984675, 0.59552461, 0.87636693, 0.40709845]])

In [74]:
A, B, C, D = np.hsplit(random_array, 4)
A

array([[0.98708152],
       [0.81031061],
       [0.93603482],
       [0.42984675]])

In [75]:
B

array([[0.61235283],
       [0.77476048],
       [0.54644815],
       [0.59552461]])

In [76]:
C

array([[0.95699754],
       [0.07428372],
       [0.51919619],
       [0.87636693]])

In [77]:
D

array([[0.75067718],
       [0.62770638],
       [0.47061915],
       [0.40709845]])

### Adding and Removing Elements

In [79]:
array_2d = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

In [80]:
add = [17,18,19,20]

In [83]:
new_array = np.append(array_2d,add)
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [84]:
new_array = np.insert(array_2d,2,add)
new_array

array([ 1,  2, 17, 18, 19, 20,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16])

In [91]:
new_array2 = np.delete(array_2d,2)
new_array2

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [87]:
# delete based on condition 

In [98]:
original_array = np.array([1, 2, 3, 4, 5])
condition = original_array > 3
new_array3 = original_array[~condition]
new_array3 


array([1, 2, 3])

### Flattening and Flattening with Fortran Order

In [108]:
original_array = np.array([[4, 3, 6],
                           [5, 1, 2]])
original_array

array([[4, 3, 6],
       [5, 1, 2]])

In [109]:
flattened_array = original_array.flatten()
flattened_array

array([4, 3, 6, 5, 1, 2])

In [ ]:
# Flattening with Fortran Order (Column-Major Order)

In [111]:
flattened_array = original_array.flatten(order = 'F')
flattened_array

array([4, 5, 3, 1, 6, 2])

In [115]:
array1 = np.array([
    [1, 8, 9, 16],
    [2, 7, 10, 15],
    [3, 6, 11, 14],
    [4, 5, 12, 13]
])

### Repeating and Tilings

In [6]:
original_array = np.array([[4, 3, 6],
                           [5, 1, 2]])

In [7]:
repeated_array = np.repeat(original_array,3)
repeated_array

array([4, 4, 4, 3, 3, 3, 6, 6, 6, 5, 5, 5, 1, 1, 1, 2, 2, 2])

In [9]:
repeated_array = np.repeat(original_array, 3, axis = 0)
repeated_array

array([[4, 3, 6],
       [4, 3, 6],
       [4, 3, 6],
       [5, 1, 2],
       [5, 1, 2],
       [5, 1, 2]])

In [ ]:
tiled_array = np.tile(original_array,3)
tiled_array

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

### Changing Data Type

In [141]:
original_array = np.array([1, 2, 3])
print(original_array.dtype)
print(original_array)
original_array.size

int32
[1 2 3]


3

In [140]:
flot_array = original_array.astype(np.float32)
print(flot_array.dtype)
print(flot_array)
flot_array.size

float32
[1. 2. 3.]


3

In [139]:
int_array = flot_array.astype(np.int64)
print(int_array.dtype)
print(int_array)
flot_array.size

int64
[1 2 3]


3

### Sorting Arrays

In [142]:
original_array = np.array([[3, 1, 5],
                           [2, 4, 6]])

In [143]:
np.sort(original_array)

array([[1, 3, 5],
       [2, 4, 6]])

In [144]:
np.sort(original_array, axis = 0)

array([[2, 1, 5],
       [3, 4, 6]])

### Searching Arrays

In [167]:
original_array = np.array([3, 1, 5, 4, 6])
original_array

array([3, 1, 5, 4, 6])

In [168]:
np.where(original_array > 3)

(array([2, 3, 4], dtype=int64),)

### Unique Values and Counts

In [170]:
original_array = np.array([3, 1, 5, 4, 6, 3, 5])
original_array

array([3, 1, 5, 4, 6, 3, 5])

In [171]:
np.unique(original_array)

array([1, 3, 4, 5, 6])

In [184]:
A, B = np.unique(original_array, return_counts=True)

In [185]:
print(A)
print(B)

[1 3 4 5 6]
[1 2 1 2 1]


### Masked Arrays

In [186]:
import numpy.ma as ma

In [187]:
data = np.array([1, 2, -999, 4, -999, 6, 7, -999])
data

array([   1,    2, -999,    4, -999,    6,    7, -999])

In [189]:
mask = ( data == -999)
mask

array([False, False,  True, False,  True, False, False,  True])

In [193]:
masked_data = ma.masked_array(data, mask)
masked_data

masked_array(data=[1, 2, --, 4, --, 6, 7, --],
             mask=[False, False,  True, False,  True, False, False,  True],
       fill_value=999999)

### Fancy Indexing and Index Tricks

In [195]:
original_array = np.array([1, 2, 3, 4, 5])

In [201]:
selected_elements = original_array[np.array([3,4])]
selected_elements

array([4, 5])

In [207]:
x = np.arange(6)
y = np.arange(2)
xx, yy = np.meshgrid(x, y)

In [211]:
print(x) # Y number of rows of X
xx

[0 1 2 3 4 5]


array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [210]:
print(y) # X number of column of Y
yy

[0 1]


array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1]])

### Diagonal and Trace

In [212]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [214]:
diagonal_elements = np.diagonal(matrix)
diagonal_elements

array([1, 5, 9])

In [215]:
trace = np.trace(matrix)
trace

15

### Flipping and Rotating

In [216]:
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

In [217]:
np.fliplr(original_array)  # last column to first column

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [219]:
np.flipud(original_array)  # last row to first row

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [220]:
np.rot90(original_array)  

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])