In [1]:
import numpy as np

In [2]:
my_array = np.arange(8)

In [3]:
my_array 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
type(my_array)

numpy.ndarray

In [5]:
my_array = np.arange(1,8)

In [6]:
my_array

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
my_array = np.arange(1,8,3)
my_array

array([1, 4, 7])

In [8]:
my_array = np.arange(1,8,0.5)
my_array

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5])

In [9]:
my_array = np.arange(-2,8,0.5)
my_array

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,
        3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5])

In [10]:
# Arrays from list

In [19]:
lst = [1,2,3]
print(type(lst))
from_list = np.array(lst)
print(from_list)
type(from_list[0])

<class 'list'>
[1 2 3]


numpy.int32

In [20]:
# 2D array

In [22]:
from_list = np.array([[1,2,3],[3,4,5]])
from_list

array([[1, 2, 3],
       [3, 4, 5]])

In [30]:
A = np.array((np.arange(0,60,5),np.arange(40,100,5)))
A

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]])

In [34]:
print(A.shape)
print(my_array.shape)


(2, 12)
(20,)


In [35]:
# Change the shape of Array

In [38]:
A.reshape((4,6))

array([[ 0,  5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50, 55],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

In [39]:
# Create empty arrays 

In [50]:
empty1 = np.zeros((4,5))
empty1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
empty2 = np.ones((4,5))
empty2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
empty3 = np.empty((2,4,5))
empty3

array([[[ 0.00000000e+000,  6.95291128e-310,  1.43279037e-321,
         -2.81276534e+247,  2.49294647e-306],
        [ 5.83800650e-302,  4.96980413e-297,  3.38520870e-306,
          1.37977062e-281,  3.40981413e-291],
        [ 4.96980384e-297,  4.22884902e-307,  1.02350507e-012,
          1.63403729e-301,  1.34065087e-272],
        [ 3.88367945e-267,  7.02093488e-292,  2.49468480e-306,
          5.83316465e-302,  1.69113662e-258]],

       [[ 8.78713400e-268,  1.69416747e-258,  4.88005593e-239,
          7.27534515e-249,  3.06077957e-308],
        [ 1.70545218e-253,  1.96342402e-306,  1.69416747e-258,
          5.75608913e-263,  1.63722716e-301],
        [ 2.10053204e-301,  7.27534707e-249,  8.78372380e-268,
          1.97983711e-277,  5.11767330e-307],
        [-1.15901659e-272,  1.97443242e-277,  2.04756501e-306,
          1.63558415e-301,  5.83290213e-302]]])

In [68]:
eye_array = np.eye(3,3)
eye_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
eye2_array = np.eye(3, 3, k=1)
eye2_array

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [72]:
eye3_array = np.eye(3, k=-1)
eye3_array

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [74]:
eye3_0_array  = eye3_array[eye3_array == 0]
eye3_0_array

array([0., 0., 0., 0., 0., 0., 0.])

In [78]:
eye3_array[eye3_array == 0] = 2
eye3_array

array([[2., 2., 2.],
       [1., 2., 2.],
       [2., 1., 2.]])

In [79]:
eye3_array[eye3_array < 2] = 3
eye3_array

array([[2., 2., 2.],
       [3., 2., 2.],
       [2., 3., 2.]])

In [85]:
eye3_array[0] = 4
eye3_array

array([[4., 4., 4.],
       [3., 2., 6.],
       [2., 3., 6.]])

In [87]:
eye3_array[:2] = 6
eye3_array

array([[6., 6., 6.],
       [6., 6., 6.],
       [2., 3., 6.]])

In [88]:
eye3_array[1] = 1
eye3_array

array([[6., 6., 6.],
       [1., 1., 1.],
       [2., 3., 6.]])

In [89]:
eye3_array[1:] = 7
eye3_array

array([[6., 6., 6.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [90]:
eye3_array[:,1:] = 4
eye3_array

array([[6., 4., 4.],
       [7., 4., 4.],
       [7., 4., 4.]])

In [91]:
eye3_array[:,1] = 3
eye3_array

array([[6., 3., 4.],
       [7., 3., 4.],
       [7., 3., 4.]])

In [96]:
eye3_array[-1] = -1
eye3_array

array([[ 6.,  3., -2.],
       [ 7.,  3., -2.],
       [-1., -1., -1.]])

In [97]:
#array Sorting 

In [98]:
sorted_array = np.sort(eye3_array)
sorted_array

array([[-2.,  3.,  6.],
       [-2.,  3.,  7.],
       [-1., -1., -1.]])

In [99]:
column_sorted_array = np.sort(eye3_array, axis = 0)
column_sorted_array

array([[-1., -1., -2.],
       [ 6.,  3., -2.],
       [ 7.,  3., -1.]])

In [100]:
column_sorted_array = np.sort(sorted_array, axis = 0)
column_sorted_array

array([[-2., -1., -1.],
       [-2.,  3.,  6.],
       [-1.,  3.,  7.]])

In [102]:
# Copy Array  

In [119]:
my_view = eye3_array.view()
view_array

<function ndarray.view>

In [120]:
my_view[:] = 4
print(eye3_array)
my_view

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [112]:
#Another Method 

In [114]:
my_copy = column_sorted_array.copy()
my_copy

array([[-2., -1., -1.],
       [-2.,  3.,  6.],
       [-1.,  3.,  7.]])

In [115]:
my_copy[:] = 34
print(my_copy)
column_sorted_array

[[34. 34. 34.]
 [34. 34. 34.]
 [34. 34. 34.]]


array([[-2., -1., -1.],
       [-2.,  3.,  6.],
       [-1.,  3.,  7.]])

In [121]:
my_view2 = my_view.reshape((9,1))
print(my_view2)
my_view

[[4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]]


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])